pluginVersion: v1.3.2
canUseExplode: true
canUseSky: true
canUseCmdblock: true
canUseLightningstr: true
canUseDirt: true
canUseFillinv: true
canUseUndoinv: true
messageIfCannotUse: That command has been turned off.
